// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDnqFE3g3CYxdSFDisy8CHmvZmNKtKkuA',
    appId: '1:230963919991:web:7cb74e130d64f7eaf3da72',
    messagingSenderId: '230963919991',
    projectId: 'quansa-homework',
    authDomain: 'quansa-homework.firebaseapp.com',
    storageBucket: 'quansa-homework.appspot.com',
    measurementId: 'G-MNLQPJY4Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARRVM0QbDsmipqvzyiUw8dLfuibNeA7lw',
    appId: '1:230963919991:android:5bfab93795a89762f3da72',
    messagingSenderId: '230963919991',
    projectId: 'quansa-homework',
    storageBucket: 'quansa-homework.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaCMax3-e3CTaiKkosbQlA1rYXDzN-YfU',
    appId: '1:230963919991:ios:13f236ce134bd973f3da72',
    messagingSenderId: '230963919991',
    projectId: 'quansa-homework',
    storageBucket: 'quansa-homework.appspot.com',
    iosClientId: '230963919991-dl8lj1hgen9kre6077umhc8s13cgpahg.apps.googleusercontent.com',
    iosBundleId: 'com.example.quansaHomework',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaCMax3-e3CTaiKkosbQlA1rYXDzN-YfU',
    appId: '1:230963919991:ios:13f236ce134bd973f3da72',
    messagingSenderId: '230963919991',
    projectId: 'quansa-homework',
    storageBucket: 'quansa-homework.appspot.com',
    iosClientId: '230963919991-dl8lj1hgen9kre6077umhc8s13cgpahg.apps.googleusercontent.com',
    iosBundleId: 'com.example.quansaHomework',
  );
}
